# Generated by Django 3.2.7 on 2021-09-03 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='score',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='scores.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='score',
            name='comments',
            field=models.TextField(default='Helping people to pray', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='score',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 8, 10, 52, 679246, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='score',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Music Sheet'),
        ),
        migrations.AddField(
            model_name='score',
            name='publication_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
