# Generated by Django 3.2.7 on 2021-10-07 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20210903_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PENDING', max_length=250, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['created'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 11, 14, 45, 130245)),
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.status')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
                'ordering': ['created'],
            },
        ),
    ]
