# Generated by Django 3.2.7 on 2021-11-23 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20211007_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 15, 21, 29, 170912)),
        ),
    ]
