# Generated by Django 3.2.7 on 2021-11-24 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_score_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 7, 2, 10, 372915)),
        ),
    ]
