# Generated by Django 3.2.7 on 2021-11-24 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_alter_score_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
