# Generated by Django 3.2.7 on 2021-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
